### PR TITLE
Add Valencia Fusion Exchange

### PR DESCRIPTION
**Pull request by marcin-wosinek**

### CODE REVIEW

**Review by LGro — APPROVED** [review]
Thanks for the support @marcin-wosinek, and apologies for the delay :relaxed:

**Comment by marcin-wosinek** [comment]
No worries—there is still plenty of time until the event:)

Thanks for your work maintaining this site. It's a great resource for finding events. Out of curiosity—do you know how many visits the website gets?

**Comment by LGro** [comment]
The only indicator I have is the analytics from the embedded Vimeo video, which shows 80-100 unique impressions per month - so that's at least a lower bound.

**Comment by marcin-wosinek** [comment]
Nice!

If you would like to add proper, privacy-oriented analytics, I have some room in my https://plausible.io subscription.

**Comment by LGro** [comment]
Thanks for the offer. Since I currently don't have any hypotheses that I would like to test with analytics or time to derive actions from them, I wouldn't add more analytics at the moment. However, should you like to get more involved with the website maintenance and have ideas or questions where that would help, I'd be open to discuss it; Feel free to drop me an email in that case.

**Comment by marcin-wosinek** [comment]
@LGro thanks for the offer! For now, I see no need for bigger updates to the website, but I definitively will keep on contributing with info about events I know about, or with some issue I notice.

**Pull request merged**
